//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vluCanteenAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int Quantity { get; set; }
        public int Bill_ID { get; set; }
        public int Food_ID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Food1 Food1 { get; set; }
    }
}
