//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vluCanteenAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Feedback_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Feedback_Meal { get; set; }
        public string Note { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual User User { get; set; }
    }
}
